apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quinoa-wind-turbine-7z84
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/nshprai-tenant/quinoa-wind-turbine/quinoa-wind-turbine-7z84@sha256:dee137890e90fc50e9e89146daecc53da886f847eeaba036e24b87f526e3e3d6
        name: my-java-quarkus
        resources: {}
status: {}
