apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine-7z84
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine-7z84
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: quinoa-wind-turbine-7z84atsl
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: quinoa-wind-turbine-7z84
    weight: null
status: {}
